language: node_js
node_js:
    - "8"
dist: trusty
script:
    - make ci
cache:
  directories:
    - tests/elm-stuff/build-artifacts
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=google-chrome-stable
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
