language: node_js
node_js:
    - "8"
dist: trusty
before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
    - make ci
addons:
  chrome: stable
