language: node_js
node_js:
    - "8"
dist: trusty
script:
    - make ci
cache:
  directories:
    - tests/elm-stuff/build-artifacts
before_script:
  - export CHROME_BIN=google-chrome-stable
addons:
  chrome: stable
