language: node_js
node_js:
    - "8"
dist: trusty
addons:
  chrome: stable
before_script:
    - export CHROME_BIN=google-chrome-stable
script:
    - make ci
cache:
  directories:
    - tests/elm-stuff/build-artifacts
